Update patch set 5
Patch Set 5:

> sorry, didn't mean to answer incomplete :(
 > The error i get ...
 > ERROR: $lineage$/packages/apps/Eleven/src/com/cyanogenmod/eleven/MusicPlaybackService.java:3478:
 > The type MusicPlaybackService.ServiceStub must implement the
 > inherited abstract method IElevenService.setVisualizer(boolean)
 > 
 > as this is the only change in eleven, could it be related?

You probably picked the change before it was merged. The previous patchset changed the definition of the service, but the one merged doesn't. Make sure your sources are exactly the same as the one in the official repo. If they are, make clean.

Patch-set: 5